site_name: Jonas Sinjan
site_url: https://jonassinjan.com
site_description: >-
  A simple static homepage for an academic researcher

copyright: Copyright (c) 2023 Jonas Sinjan

# Page tree
nav:
  - Home: index.md
  - About: 
    - about/index.md
    - Hobbies: about/hobbies.md
  - CV: 
    - Education: cv/education.md 
    - Experience: cv/experience.md
    - Skills: cv/skills.md
    - Professional Service: cv/professional_service.md
    - Publications: cv/publications.md
    - Talks: cv/talks.md
  - Projects: 
    - projects/index.md
    - PhD: 
      - SO/PHI SOAR Download: projects/soar_download.md
      - SO/PHI-HRT and SDO/HMI file loader: projects/hrt_and_hmi_files.md
      - SO/PHI-HRT WCS Correction: projects/sophihrt_wcs_corr.md
      
  - MSci: 
    - msci/index.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

# Additional configuration
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JonasSinjan
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jonassinjan
    - icon: simple/googlescholar
      link: https://scholar.google.com/citations?user=AXjToZAAAAAJ&hl=en
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-5387-636X

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all

